---
- name: Get Tenant List
  hosts:
    - apic
  gather_facts: false
  connection: local
  
  tasks:
    - name: login
      include_vars: creds.yaml
    - name: Get tenants from APIC(s)
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ apic_username }}"
        password: "{{ apic_password }}"
        method: get
        path: /api/node/class/fvTenant.json
        validate_certs: no
      delegate_to: localhost
      register: tenant_list
    - name: Print tenant list
      debug:
        var: tenant_list
